### ISSUE TITLE
发现一个问题，会覆盖资源

### ISSUE THREAD

**Issue by skypjsfly** [VergilGao/docker-avdc#12]
如果一个片有多个文件，有一种命名方式是XXX-XXX.cd1.mp4 XXX-XXX.cd2.mp4
如果是这样的话，刮削后会重命名文件为XXX-XXX.mp4，然后cd2会覆盖掉cd1，文件夹中最后只剩一个视频文件
如果是XXX-XXX-cd1.mp4则不会有这个问题

**Comment by VergilGao** [comment]
https://github.com/yoshiko2/AV_Data_Capture/wiki#%E5%A4%9A%E7%9B%AE%E5%BD%95%E5%BD%B1%E7%89%87%E5%A4%84%E7%90%86

**Comment by skypjsfly** [comment]
这个我知道，但是emby默认的多集处理是.cdn而不是-cdn

**Comment by VergilGao** [comment]
> 这个我知道，但是emby默认的多集处理是.cdn而不是-cdn

请去原仓库反馈。
