### ISSUE TITLE
在群暉裡一開就掛掉

### ISSUE THREAD

**Issue by mcdull** [VergilGao/docker-avdc#15]
3.9.2 什麼也沒設定,  只映射了/jav/data
開著container, log 出現
found 0 movies 
All finished

container 就掛掉了
但 /jav/data 是有文檔的

EDIT
原來已改做 /app/data

另外, 看來這個 docker 的設計就是完結時自動掛掉. 那就好像沒有用 docker 的必要, 還不如開個shell 來處理.

**Comment by VergilGao** [comment]
防止依赖冲突。
