### ISSUE TITLE
刚刚试了一下成功了，请问下一次需要整理的时候要输入什么命令让这个程序运行？

### ISSUE THREAD

**Issue by gcphym** [VergilGao/docker-avdc#16]

**Comment by VergilGao** [comment]
启动时加 --rm 参数可以运行后自动删除镜像。
下次用一样的参数就好了。

如果不想每次都输入参数，可以考虑
1. 自己写一个bash脚本
2. docker-compose

**Comment by gcphym** [comment]
> 启动时加 --rm 参数可以运行后自动删除镜像。
> 下次用一样的参数就好了。
> 
> 如果不想每次都输入参数，可以考虑
> 
> 1. 自己写一个bash脚本
> 2. docker-compose

啊这 不会写 目前我的解决方法是cron间隔执行 这样新下载的就能自动被扫到了
