### ISSUE TITLE
关于本仓库下一步的发展规划

### ISSUE THREAD

**Issue by VergilGao** [VergilGao/docker-avdc#18]
因为平时工作比较忙，所以对于本仓库的更新也一直很不上心，目前本仓库提供的avdc版本仍停留在3.9.2，最近可能会同步更新到上游4.2.2
因为我个人使用avdc时，主要还是手动刮削整理，所以当前avdc源程序提供的功能已经满足了我的使用需求，所以对于很多人想要的自动刮削我并没有开发的动力（其实仿照iyuu的docker那样做一个cron也可以，但是我认为这不应该是docker要做的，而是需要用户手动在宿主系统里写cron来做），docker版本最重要的功能应该是解决程序运行环境的问题，毕竟glibc版本更新对于小白用户来说是一个非常危险的操作。
也许明年我会照着上游写一个自动编译二进制来发布的功能，降低镜像的体积。但是这个优先度还是很低，因为本镜像的体积相对于大姐姐的体积而言，并不算大。

对于用户来说，我建议使用本仓库程序的一个思路是：
pt或者bt下载完成->自动运行脚本硬链接到avdc文件夹，cron定时刮削并将output文件夹内的文件硬链接到jellyfin、plex等媒体库。

**Comment by frosty5689** [comment]
+1 我现在就是用cron运行一个简单的Bash script, 运行这个Docker分类文件，然后用rsync批量移动。因为我Plex的媒体文件在NAS上（BT下载用淘汰的老硬盘）， 所以传输时间比较长，用rsync可以即使调查进度适合传高清文件。Docker本身就应该运行一个程序，目的是结局运行环境设置复杂的问题和避免更高主机os。如果Docker自己带cron或者sleep之类的就失去灵活性了。除非目的是用inotify来监控一个文件目录而做到即时分类。。不过这样很难判断BT已经下载完毕还是不要的好。

我个人流程是：BT下载到临时目录->BT下载完成存到完成目录->cron定期运行avdc分类紧接着运行rsync移动到plex媒体文件夹

Docker本身能跟上avdc的版本更新并支持用ENV var设置更多的参数就可以了。

**Comment by VergilGao** [comment]
> +1 我现在就是用cron运行一个简单的Bash script, 运行这个Docker分类文件，然后用rsync批量移动。因为我Plex的媒体文件在NAS上（BT下载用淘汰的老硬盘）， 所以传输时间比较长，用rsync可以即使调查进度适合传高清文件。Docker本身就应该运行一个程序，目的是结局运行环境设置复杂的问题和避免更高主机os。如果Docker自己带cron或者sleep之类的就失去灵活性了。除非目的是用inotify来监控一个文件目录而做到即时分类。。不过这样很难判断BT已经下载完毕还是不要的好。
> 
> 我个人流程是：BT下载到临时目录->BT下载完成存到完成目录->cron定期运行avdc分类紧接着运行rsync移动到plex媒体文件夹
> 
> Docker本身能跟上avdc的版本更新并支持用ENV var设置更多的参数就可以了。

qb和tr都有下载后执行命令的功能，可以设置下载后使用命令将下载好的文件硬链接到指定目录，然后就可以边刮削边做种了。
刮削完后再rsync

**Comment by frosty5689** [comment]
嗯，我用的Deluge。也有这功能不过我是做种到目标ratio后移动到别的目录后才会分类。因为下载用的硬盘不大存不了那么多。hardlink的话分类完了是移动到NAS里的。😂
