### ISSUE TITLE
已经测试，可以了，谢谢大佬。

### ISSUE THREAD

**Issue by christdl** [VergilGao/docker-avdc#2]
简单补充一下安装教程，给使用群晖docker的小白们：
1.根据大佬的教程，测试通过以后，打开docker在映像里面会多出一个下载好的新映像：vergilgao/avdc
2.双击这个新映像，进入安装界面，进入高级设置--卷--添加文件夹，选择“你放大姐姐影片的文件夹”，装载路径填上：/jav/data
3.其他都不用管，一直下一步，完成创建容器。
4.运行这个容器，如果你的文件夹里面有下载好的影片，就会归档了。具体可以在容器的日志里面查看。
最后，感谢大佬的辛苦付出，再次拜谢！！！

**Comment by VergilGao** [comment]
简单使用已经可以了，但还不是那么特别完善。
下一步准备用 s6-overlay 来完善一下文件系统权限，此外我还打算增加环境变量，让自定义设置更简单一些。

**Comment by christdl** [comment]
能用就好，嘿嘿。另外，只要把config文件映射出来，就可以自己配置参数了吧。config的装载地址是多少？是不是：/jav/config.ini

**Comment by christdl** [comment]
另外，还可以在群晖里面设置自动运行这个docker，基本已经实现一条龙自动化了。
理论上，只要在网站上看到喜欢的小姐姐，直接右键“Download with Downloadstation”，后面就不用管了，会自动下载好，在你设定的时间自动归档好。
具体等试运行一段时间看看再说。

**Comment by VergilGao** [comment]
> 能用就好，嘿嘿。另外，只要把config文件映射出来，就可以自己配置参数了吧。config的装载地址是多少？是不是：/jav/config.ini

config文件这里要参考我readme里面的配置来改，一定要把目录设置为 data/output data/failed 这样的格式。
不设置为 data 目录下会出问题。

**Comment by MichaelthA** [comment]
大佬，我发现你还没说config.ini的位置在哪里，群晖上面不知道位置的话是没办法映射修改的

**Comment by MichaelthA** [comment]
> 另外，还可以在群晖里面设置自动运行这个docker，基本已经实现一条龙自动化了。
> 理论上，只要在网站上看到喜欢的小姐姐，直接快捷“使用Downloadstation下载”，后面就不用管了，会自动下载好，在你设定的时间自动排列好，然后就会出现在Jellyfin的展示页面。赞！
> 具体等试运行放置看看再说。



> 能，就好，嘿嘿。另外，只要把配置文件映射出来，就可以自己配置参数了吧。config的装载地址是多少？是不是：/jav/config.ini

hxd，config.ini这玩意儿是映射在哪里啊？你解决了吗。我这边动不动就报错Connect Failed! Please check your Proxy or Network!，我想给他搞上科学上网

**Comment by VergilGao** [comment]
> 大佬，我发现你还没说config.ini的位置在哪里，群晖上面不知道位置的话是没办法映射修改的

我没用过群晖，所以不太清楚。

下周我看看能不能把配置全部变成环境变量，这两天在忙活verysync

**Comment by christdl** [comment]
> > 另外，还可以在群晖里面设置自动运行这个docker，基本已经实现一条龙自动化了。
> > 理论上，只要在网站上看到喜欢的小姐姐，直接快捷“使用Downloadstation下载”，后面就不用管了，会自动下载好，在你设定的时间自动排列好，然后就会出现在Jellyfin的展示页面。赞！
> > 具体等试运行放置看看再说。
> 
> > 能，就好，嘿嘿。另外，只要把配置文件映射出来，就可以自己配置参数了吧。config的装载地址是多少？是不是：/jav/config.ini
> 
> hxd，config.ini这玩意儿是映射在哪里啊？你解决了吗。我这边动不动就报错Connect Failed! Please check your Proxy or Network!，我想给他搞上科学上网

我是在路由器上配置的，所有就不需要单独配置。我猜是不是在/jav的根目录下面，具体没去找过

**Comment by VergilGao** [comment]
> > 另外，还可以在群晖里面设置自动运行这个docker，基本已经实现一条龙自动化了。
> > 理论上，只要在网站上看到喜欢的小姐姐，直接快捷“使用Downloadstation下载”，后面就不用管了，会自动下载好，在你设定的时间自动排列好，然后就会出现在Jellyfin的展示页面。赞！
> > 具体等试运行放置看看再说。
> 
> > 能，就好，嘿嘿。另外，只要把配置文件映射出来，就可以自己配置参数了吧。config的装载地址是多少？是不是：/jav/config.ini
> 
> hxd，config.ini这玩意儿是映射在哪里啊？你解决了吗。我这边动不动就报错Connect Failed! Please check your Proxy or Network!，我想给他搞上科学上网

我发布了一个测试镜像，tag是3.9.1-beta
docker pull vergilgao/avdc:3.9.1-beta
在启动时加入两个环境变量
-e PROXY_TYPE=代理类型，http or socks5 or socks5h
-e PROXY_URI=代理地址，如127.0.0.1:1080
来自定义代理。

**Comment by MattFirefly** [comment]
这个库对和原版的有什么区别？

**Comment by VergilGao** [comment]
> 这个库对和原版的有什么区别？ 映射的路径应该是那个/jav/data /app/data 显示都 Find 0 movies

3.9.1 映射目录是 /jav/data
3.9.1-beta 映射的目录是 /app/data

看一下你docker镜像的tag
3.9.1 这个 tag 因为设计变动我不准备给他写readme了。
