### ISSUE TITLE
location_rule参数无法建立多级目录

### ISSUE THREAD

**Issue by brighteast1988** [VergilGao/docker-avdc#20]
日志：
[!]Making Data for [./data/VEMA-155.mp4], the number is [VEMA-155]
[-] [./data/VEMA-155.mp4] ERROR:
[-] invalid syntax (<string>, line 1)
[-]Move [./data/VEMA-155.mp4] to failed folder
[+]All finished!!!

我是这么配置的：
docker run --rm -it \
 --name avdc_test \
 -v ${PWD}:/app/data  \
 -e USE_PROXY=0  \
 -e RETRY=2 \
 -e TIMEOUT=5 \
 -e PRIORITY_WEBSITE=javbus \
 -e LOCATION_RULE=actor+'/'+title \
 -e NAMING_RULE=number \
 vergilgao/avdc:latest

**Comment by brighteast1988** [comment]
补充一下，不建立多级目录的情况下 可以正常刮削

**Comment by VergilGao** [comment]
```-e LOCATION_RULE="actor+'/'+title"```
用英文双引号
