### ISSUE TITLE
折腾5小时左右，代理设置始终不成功

### ISSUE THREAD

**Issue by sirliu** [VergilGao/docker-avdc#22]
环境：CentOS-8.3.211（64），Docker version 20.10.6, build 370c289
宿主机已经设置了sock5代理（端口是1280），宿主机平时通过privoxy将HTTP协议流量转发到本地sock5。
但是使用`docker-avdc`容器，将代理指向宿主机的1280端口，提示代理错误。
而宿主机访问google，javbus都是正常的.
下面是我的run参数
```bash
docker run --rm -it \
  --name avdc_test \
  -v /test:/app/data \
  -e USE_PROXY=1 \
  -e PROXY_TYPE="socks5" \
  -e PROXY_URI="127.0.0.1:1280" \
  vergilgao/avdc:latest
```

**Comment by VergilGao** [comment]
`
docker run --rm -it \
  --net=host \
  --name avdc_test \
  -v /test:/app/data \
  -e USE_PROXY=1 \
  -e PROXY_TYPE="socks5" \
  -e PROXY_URI="127.0.0.1:1280" \
  vergilgao/avdc:latest
`
要用host模式来运行。

**Comment by sirliu** [comment]
> ```
> docker run --rm -it \
>   --net=host \
>   --name avdc_test \
>   -v /test:/app/data \
>   -e USE_PROXY=1 \
>   -e PROXY_TYPE="socks5" \
>   -e PROXY_URI="127.0.0.1:1280" \
>   vergilgao/avdc:latest
> ```
> 
> 加一行--net=host
> 热知识，默认的docker镜像使用网桥模式运行，此时容器内无法直接访问宿主机网络，容器内的 127.0.0.1 和宿主的 127.0.0.1并不等价。
> 
> 简单起见直接用host模式来运行就好了。
> 
> 最近在加班，如果有什么问题可以留言，我晚上到家会看。

增加net=host这个参数我也试过，也报错，
```
[root@localhost ~]# docker run --rm -it   --name avdc_test   -v /mnt/data_part/webdav_server/test:/app/data --net=host  -e USE_PROXY=1   -e PROXY_TYPE="socks5"   -e PROXY_URI="127.0.0.1:1280"   vergilgao/avdc:latest
[*]================== AV Data Capture ===================
[*]                        4.5.1                         
[*]======================================================
[+]Find 1000 movies
[!] - 0.1% [1/1000] -
[!]Making Data for [/app/data/ffdsds/PPPD-391.mp4], the number is [PPPD-391]
/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.fanbus.us'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cn.airav.wiki'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.javbus.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.javbus.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.fanbus.us'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
[+]Image Downloaded! data/output/JULIA/PPPD-391/PPPD-391-fanart.jpg
[+]Image Cutted!     data/output/JULIA/PPPD-391/PPPD-391-poster.jpg
[+]Wrote!            data/output/JULIA/PPPD-391/PPPD-391.nfo
[*]======================================================
[!] - 0.2% [2/1000] -
[!]Making Data for [/app/data/ffdsds/PPPD-1.mp4], the number is [PPPD-1]
/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.fanbus.us'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.javbus.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.javbus.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cn.airav.wiki'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cn.airav.wiki'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.javbus.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
[-]Movie Data not found!
[-]Move to Failed output folder
[-] [/app/data/ffdsds/PPPD-1.mp4] ERROR:
[-] [Errno 2] No such file or directory: '/app/data/ffdsds/data/failed/'
[-]Move [/app/data/ffdsds/PPPD-1.mp4] to failed folder
[!] - 0.3% [3/1000] -

```
另外，我还试过以下，几个方式，均失败告终。

1. 只使用net=host，其他环境变量去掉
2. 在docker demon的配置文件中加入代理，以期实现docker容器全部都能自动走代理

**Comment by VergilGao** [comment]
> > ```
> > docker run --rm -it \
> >   --net=host \
> >   --name avdc_test \
> >   -v /test:/app/data \
> >   -e USE_PROXY=1 \
> >   -e PROXY_TYPE="socks5" \
> >   -e PROXY_URI="127.0.0.1:1280" \
> >   vergilgao/avdc:latest
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 加一行--net=host
> > 热知识，默认的docker镜像使用网桥模式运行，此时容器内无法直接访问宿主机网络，容器内的 127.0.0.1 和宿主的 127.0.0.1并不等价。
> > 简单起见直接用host模式来运行就好了。
> > 最近在加班，如果有什么问题可以留言，我晚上到家会看。
> 
> 增加net=host这个参数我也试过，也报错，
> 
> ```
> [root@localhost ~]# docker run --rm -it   --name avdc_test   -v /test:/app/data --net=host  -e USE_PROXY=1   -e PROXY_TYPE="socks5"   -e PROXY_URI="127.0.0.1:1280"   vergilgao/avdc:latest
> [*]================== AV Data Capture ===================
> [*]                        4.5.1                         
> [*]======================================================
> [+]Find 1000 movies
> [!] - 0.1% [1/1000] -
> [!]Making Data for [/app/data/ffdsds/PPPD-391.mp4], the number is [PPPD-391]
> /usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.fanbus.us'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   warnings.warn(
> /usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cn.airav.wiki'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   warnings.warn(
> /usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.javbus.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   warnings.warn(
> /usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.javbus.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   warnings.warn(
> /usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.fanbus.us'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   warnings.warn(
> [+]Image Downloaded! data/output/JULIA/PPPD-391/PPPD-391-fanart.jpg
> [+]Image Cutted!     data/output/JULIA/PPPD-391/PPPD-391-poster.jpg
> [+]Wrote!            data/output/JULIA/PPPD-391/PPPD-391.nfo
> [*]======================================================
> [!] - 0.2% [2/1000] -
> [!]Making Data for [/app/data/ffdsds/PPPD-1.mp4], the number is [PPPD-1]
> /usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.fanbus.us'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   warnings.warn(
> /usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.javbus.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   warnings.warn(
> /usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.javbus.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   warnings.warn(
> /usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cn.airav.wiki'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   warnings.warn(
> /usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cn.airav.wiki'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   warnings.warn(
> /usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.javbus.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   warnings.warn(
> [-]Movie Data not found!
> [-]Move to Failed output folder
> [-] [/app/data/ffdsds/PPPD-1.mp4] ERROR:
> [-] [Errno 2] No such file or directory: '/app/data/ffdsds/data/failed/'
> [-]Move [/app/data/ffdsds/PPPD-1.mp4] to failed folder
> [!] - 0.3% [3/1000] -
> ```
> 
> 另外，我还试过以下，几个方式，均失败告终。
> 
> 1. 只使用net=host，其他环境变量去掉
> 2. 在docker demon的配置文件中加入代理，以期实现docker容器全部都能自动走代理

我检查了上游仓库的release，没有发现与你描述的问题的相关修复。
建议前往上游仓库发issue来反馈问题。
我更新了一个版本，同步到了上游仓库的最新release，你可以试一下，但是我觉得应该还是会出问题。
