### ISSUE TITLE
更新到4.6 后封面变成双页面了，没有之前单页面好，有什么办法调整吗

### ISSUE THREAD

**Issue by wangrui1573** [VergilGao/docker-avdc#27]
更新到4.6 后封面变成双页面了，没有之前单页面好，缩略图看不清有什么办法调整吗？

**Comment by VergilGao** [comment]
不好意思，人在外出差，这周回家研究一下。

**Comment by wangrui1573** [comment]
看了一下，原作者已经更新了 ，可能需要你更新docker镜像
https://github.com/moyy996/AVDC

moyy996 2021-06-05-修复JAVBUS封面问题
42ea8c0

**Comment by VergilGao** [comment]
你发的这个不是原作者的仓库，是gui作者的修改。
我更新了原作者的4.6.7版本，你可以看一下是否修复了此问题。

**Comment by wangrui1573** [comment]
不确定是代理的问题还是，更新的问题，总之我更新了之后就好了，谢谢~
