### ISSUE TITLE
大佬能抽空更新下4.7.2版本吗，急需一个新feature

### ISSUE THREAD

**Issue by tyhunter** [VergilGao/docker-avdc#30]
本体4.7.2新增加的“配置文件删除空文件夹参数”，辛苦大佬抽空更新下

**Comment by VergilGao** [comment]
正在更新，默认启用了这个功能，更新完可以反馈一下这个功能是否可用。

**Comment by tyhunter** [comment]
@VergilGao 测试了下，可用，会自动删除空文件夹
[*]================== AV Data Capture ===================
[*]                        4.7.2
[*]======================================================
[*]严禁在墙内宣传本项目
[+]Find 1 movies
[!] - 100.% [1/1] -
[!]Making Data for [/app/data/RBD-315-C/RBD-315-C.mp4], the number is [RBD-315]
[+]Image Downloaded! data/output/RBD-315/RBD-315-C-fanart.jpg
[-]Connect retry 1/20
[+]Image Cutted!     data/output/RBD-315/RBD-315-C-poster.jpg
[+]Wrote!            data/output/RBD-315/RBD-315-C.nfo
[-]Connect retry 2/20
[*]======================================================
[+]Deleting empty folder /app/data/RBD-315-C
[+]Used 23.14s
[+]All finished!!!
