### ISSUE TITLE
Error Response

### ISSUE THREAD

**Issue by stephenlzc** [VergilGao/docker-avdc#6]
，在NAS上已经安装好Docker，连接SSH后，sudo -i，输入了密码，然后按照说明文档进行测试，输入docker pull vergilgao/avdc:3.9.2之后，反馈了Error response from daemon: Get https://registry-1.docker.io/v2/: EOF，请问如何解决？

**Comment by VergilGao** [comment]
请换国内的docker镜像源
参考：https://www.runoob.com/docker/docker-mirror-acceleration.html

**Comment by stephenlzc** [comment]
仍然提示permission denied

**Comment by VergilGao** [comment]
把你执行的命令和命令行反馈完整的粘贴上来，你这么说我很难判断是哪里的问题。
